import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import Button from '../Components/Button'
import CheckoutProduct from '../Components/CheckoutProduct'
import Headers from '../Components/Headers'
import { selectBasketItems, selectBasketTotal } from '../redux/basketslice'
import Currency from 'react-currency-formatter'

const Checkout = () => {
  const items = useSelector(selectBasketItems)
  const basketToatal = useSelector(selectBasketTotal)
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [groupedItemInBasket, setGroupedItemInBasket] = useState(
    {} as { [key: string]: Product[] },
  )
  useEffect(() => {
    const groupedItems = items.reduce((result, item) => {
      ;(result[item._id] = result[item._id] || []).push(item)
      return result
    }, {} as { [key: string]: Product[] })

    setGroupedItemInBasket(groupedItems)
  }, [items])
  const checkoutSession = async () => {
    setLoading(true)
  }
  return (
    <div className="min-h-screen overflow-hidden bg-[#e7ecee]">
      <Head>
        <title>Bag-Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headers />
      <main className="mx-auto max-w-4xl">
        <div className="px-5">
          <h1 className="my-4 text-3xl font-semibold lg:text-4xl">
            {items.length > 0 ? 'Review your bag' : 'Your bag is empty'}
          </h1>
          <p>Free delivery and free returns.</p>
          {items.length === 0 && (
            <Button
              title="Continue Shopping"
              onClick={() => router.push('/')}
            />
          )}
        </div>
        {items.length > 0 && (
          <div className="mx-5 md:mx-8">
            {Object.entries(groupedItemInBasket).map(([key, items]) => (
              <CheckoutProduct key={key} items={items} id={key} />
            ))}
            <div className="my-12 mt-6 ml-auto max-w-3xl">
              <div className="divide-y divide-gray-300">
                <div className="pb-4">
                  <div className="flex justify-between">
                    <p>Subtotal</p>
                    <p>
                      {' '}
                      <Currency quantity={basketToatal} currency="NPR" />
                    </p>
                  </div>
                  <div className="flex justify-between">
                    <p>Shipping</p>
                    <p>FREE</p>
                  </div>
                  <div className="flex justify-between">
                    <div className="flex flex-col gap-x-1 lg:flex-row">
                      Estimated tax for :{''}
                      <p className="flex cursor-pointer items-end text-blue-500 hover:underline">
                        Enter zip code
                      </p>
                    </div>
                    <p>Rs-</p>
                  </div>
                </div>
                <div className="flex justify-between pt-4 text-xl font-semibold mb-5">
                  <h4>Total</h4>
                  <h4>
                    {' '}
                    <Currency quantity={basketToatal} currency="NPR" />
                  </h4>
                </div>
              </div>
              <div className="my-10 space-y-4">
                <h4 className="text-xl font-semibold">
                  How would you like to check out?
                </h4>
              </div>
              <div className="flex flex-col gap-4 md:flex-row">
                <div className="order-2 flex flex-1 flex-col items-center rounded-xl bg-gray-200 p-8 py-12 text-center">
                  <h4 className="mb-4 flex flex-col text-xl font-semibold">
                    <span>Pay Monthly</span>
                    <span>with Apple Card</span>
                    <span>Rs1500/mo. at 0% APR</span>
                  </h4>
                  <Button title="check out with apple card monthly installments" />
                  <p className="mt-2 max-w-[240px] text-[13px]">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Architecto nostrum a impedit quis. Ea, veniam?
                  </p>
                </div>
                <div className="flex flex-1 flex-col items-center space-y-8 rounded-xl bg-gray-200 p-8 py-12 md:order-2">
                  <h4 className="mb-4 flex flex-col text-xl font-semibold">
                    Pay in full
                    <span>
                      {' '}
                      <Currency quantity={basketToatal} currency="NPR" />
                    </span>
                  </h4>
                  <Button
                    noIcon
                    title="Check Out"
                    width="w-full"
                    onClick={checkoutSession}
                  />
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

export default Checkout
