import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Headers from '../Components/Headers'
import LandingPage from '../Components/LandingPage'
import { Tab } from '@headlessui/react'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Apple Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headers />
      <main className="relative h-[200vh] bg-[#e7ecee]">
        <LandingPage />
      </main>
      <section className="relative z-40 -mt-[100vh] min-h-screen bg-[#1b1b1b]">
        <div className="space-y-10 py-16">
          <h1 className="text-center text-4xl font-medium tracking-wide text-white md:text-5xl">
            New Promos
          </h1>
          <Tab.Group>
            <Tab.List className="flex justify-center">
              <Tab>Tab 1</Tab>
              <Tab>Tab 2</Tab>
              <Tab>Tab 3</Tab>
            </Tab.List>
            <Tab.Panels>
              <Tab.Panel>Content 1</Tab.Panel>
              <Tab.Panel>Content 2</Tab.Panel>
              <Tab.Panel>Content 3</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </section>
    </div>
  )
}

export default Home

//backend code here
export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {},
  }
}
